AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LogVolume:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    Properties:
      AvailabilityZone: us-east-1a
      Size: 8
      Tags:
        -
          Key: Name
          Value: web-log-volume
      VolumeType: gp2