AWSTemplateFormatVersion: "2010-09-09"
Resources:
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08f3d892de259504d
      InstanceType: t2.micro
      KeyName: AWSDevOpsKey
      SecurityGroupIds:
        - sg-131e6a5b
      SubnetId: subnet-f729a3bd

  WebElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WebInstance
      Domain: vpc