AWSTemplateFormatVersion: "2010-09-09"
Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web server 100
      GroupName: web     
      VpcId: vpc-55b28b2e
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08f3d892de259504d
      KeyName: AWSDevOpsKey
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      SubnetId: subnet-f729a3bd