AWSTemplateFormatVersion: '2010-09-09'
Description: A simple EC2 instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08f3d892de259504d
      InstanceType: t2.micro
      KeyName: AWSDevOpsKey
      Monitoring: true
      SecurityGroupIds:
        - sg-131e6a5b
      SubnetId: subnet-f729a3bd
      Volumes:
        -
          Device: "/dev/sdf"
          VolumeId: !Ref LogVolume
      Tags:
        -
          Key: Name
          Value: Web Server 3

  LogVolume:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    Properties:
      AvailabilityZone: us-east-1a
      Size: 10
      Tags:
        -
          Key: Name
          Value: web-log-volume
      VolumeType: gp2