AWSTemplateFormatVersion: '2010-09-09'
Description: A simple EC2 instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
        ImageId: ami-0ff8a91507f77f867
        InstanceType: t1.micro

    Type: AWS::EC2::SecurityGroup
    Properties: 
        GroupDescription: String
        GroupName: String
        SecurityGroupEgress: 
        - Egress
        SecurityGroupIngress: 
        - Ingress
        Tags: 
        - Tag
        VpcId: String