AWSTemplateFormatVersion: "2010-09-09"
Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Linux server
      GroupName: Linux Web     
      VpcId: vpc-55b28b2e